"""Emit a config.toml file from a Config object.

We hand-roll a minimal TOML emitter for our specific schema rather than
adding a `tomli-w` dependency. The output is deterministic and re-parses
correctly with the standard `tomllib`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from documentcrawler.config import Config


def _t_str(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _t_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return _t_str(v)
    if isinstance(v, list):
        items = ", ".join(_t_value(x) for x in v)
        return f"[{items}]"
    if isinstance(v, dict):
        # Inline table - rarely used; fallback for nested dicts.
        items = ", ".join(f"{k} = {_t_value(val)}" for k, val in v.items())
        return f"{{{items}}}"
    return _t_str(str(v))


def _emit_kv(key: str, value: Any) -> str:
    return f"{key} = {_t_value(value)}\n"


def render_config_toml(cfg: Config) -> str:
    out: list[str] = []

    out.append("# documentcrawler configuration. Generated by the GUI.\n\n")

    # [general]
    g = cfg.general
    out.append("[general]\n")
    out.append(_emit_kv("download_dir", str(g.download_dir).replace("\\", "/")))
    out.append(_emit_kv("db_path", str(g.db_path).replace("\\", "/")))
    out.append(_emit_kv("filename_template", g.filename_template))
    out.append(_emit_kv("folder_template", g.folder_template))
    out.append(_emit_kv("workers", g.workers))
    out.append(_emit_kv("request_timeout_s", g.request_timeout_s))
    out.append(_emit_kv("max_retries", g.max_retries))
    out.append(_emit_kv("min_pdf_bytes", g.min_pdf_bytes))
    out.append(_emit_kv("log_level", g.log_level))
    out.append("\n")

    # [fetcher]
    out.append("[fetcher]\n")
    for host, rate in cfg.fetcher.rate_limits.items():
        out.append(f"{_quote_host(host)} = {rate}\n")
    out.append("\n[fetcher.user_agents]\n")
    out.append(_emit_kv("list", cfg.fetcher.user_agents))
    out.append("\n")

    # [metadata.*]
    for section, data in (cfg.metadata or {}).items():
        out.append(f"[metadata.{section}]\n")
        for k, v in data.items():
            out.append(_emit_kv(k, v))
        out.append("\n")

    # [sources]
    out.append("[sources]\n")
    out.append(_emit_kv("order", cfg.sources_order))
    out.append("\n")
    for name, sc in cfg.sources.items():
        out.append(f"[sources.{name}]\n")
        out.append(_emit_kv("enabled", sc.enabled))
        for k, v in sc.options.items():
            out.append(_emit_kv(k, v))
        out.append("\n")

    return "".join(out)


def _quote_host(host: str) -> str:
    """TOML keys with dots / hyphens must be quoted."""
    if all(c.isalnum() or c == "_" for c in host):
        return host
    return _t_str(host)


def write_config(cfg: Config, path: Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = render_config_toml(cfg)
    path.write_text(text, encoding="utf-8")
    return path
